language: node_js
node_js:
  - "8.9.0"
  - "9"
  - "10"
  - "11"

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage